name: first-workflow
on: workflow_dispatch
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: hello_world
              run: |
                echo "Hello, World!"
                echo "두 줄을 순차 실행할 수 있다"
